### ISSUE TITLE
How to deal with recursive structures

### ISSUE THREAD

**Issue by razaqq** [birkenfeld/serde-pickle#25]
Im dealing with pickles containing recursive structures, but i do not need the data contained in them.
Basically im trying to "ignore" recursive structures without erroring.
Currently i dont see any option to do so.
Basically im looking for something like `.replace_unresolved_globals()` but for recursive structures.

**Comment by razaqq** [comment]
Upon reading the PRs i noticed that https://github.com/birkenfeld/serde-pickle/pull/22 adds support for exactly what i asked for

**Comment by landaire** [comment]
@razaqq I'm sure you've moved past this problem, but I recommend you give my patch a try as well: https://github.com/birkenfeld/serde-pickle/pull/24

```
[patch.crates-io]
serde-pickle = { git = "https://github.com/landaire/serde-pickle.git" }
```

**Comment by birkenfeld** [comment]
Thanks for the issue, I've added the requested option now.
