### ISSUE TITLE
Using a serialized Rust model for multi-label classification prediction

### ISSUE THREAD

**Issue by DmitrySorda** [birkenfeld/serde-pickle#26]
Hi there!
I have a trained .pkl multi-label classification model. Can I use this model from Rust by serializing it into an instance of a Rust structure? Could you suggest any libraries that can make predictions from Rust?
Any guidance or examples would be greatly appreciated!

**Comment by birkenfeld** [comment]
Hi, unfortunately I know nothing about the structure of such a model. You can start with deserializing into a generic `serde_pickle::Value` and seeing how the structure looks, then you can maybe select a more fitting one, or convert it into the necessary input for a Rust library that can make predictions.
