### ISSUE TITLE
Strange handling of enums (decoding error: enums must be tuples)

### ISSUE THREAD

**Issue by Palladinium** [birkenfeld/serde-pickle#9]
`serde_pickle` handles serde's default externally-tagged enum representation differently from other serde libraries I've encountered, which can cause issues when translating the same data between multiple serialization formats.

For example, I took `serde_yaml` and `serde_json` and used their `to_string` function, while for `serde_pickle` I pickled with the pickle 3 format, unpickled in Python 3 and put the result through `print()`.

```rust
#[derive(Serialize)]
enum Foo {
    Struct { a: i32 },
    NewType(i32),
    Tuple(i32, u32),
    Unit,
}

fn values() -> Vec<Foo> {
    vec![
        Foo::Struct { a: 1 },
        Foo::NewType(2),
        Foo::Tuple(3, 4),
        Foo::Unit,
    ]
}
```
# JSON
```
[{"Struct":{"a":1}},{"NewType":2},{"Tuple":[3,4]},"Unit"]
```
# YAML
```
---
- Struct:
    a: 1
- NewType: 2
- Tuple:
    - 3
    - 4
- Unit
```
# serde-pickle
```
[('Struct', {'a': 1}), ('NewType', 2), ('Tuple', [3, 4]), ('Unit',)]
```
# What I'd expect serde-pickle to do
I think `serde-pickle` should follow the example of `serde_yaml` and `serde_json`, and (de)serialize like:
```
[{'Struct':{'a':1}},{'NewType':2},{'Tuple':[3,4]},'Unit']
```
Furthermore, if you use a python YAML or JSON library to load the above YAML or JSON examples, it'll produce the same output I'd expect `serde-pickle` to emit. (This is actually my use case, where a python script and a Rust program exchange data that is also distributed as YAML files).

**Comment by birkenfeld** [comment]
You're right, this is strange. I don't remember a reason for using a different method here.

For compatibility reasons, I'm not eager to change the serialize side, but it is no problem to accept both formats on the deserialize side. Would that be ok for your use case?

**Comment by Palladinium** [comment]
I think that would be a nice improvement, and it's completely fair to want to avoid breaking changes, but unfortunately I need to do both serialization and deserialization on the Rust side. Perhaps using a feature gate, or holding the serialize change until a new major version would make it less disruptive?

Either way, I'm mainly just using pickle since it's extremely easy to use on the Python side but I actually have the choice of using another format, so I should be able to get by with JSON.

**Comment by birkenfeld** [comment]
Yes, I may switch it for 1.0, while also changing the serializing APIs from a single bool option (for proto 3) to an extensible struct.

**Comment by jzrake** [comment]
This issue is a hard defect -- serde_pickle does not support structs which use serde's "internal" tagging convention:

```Rust
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(tag = "type")]
enum Thing {
    Thing(f64),
}

#[test]
fn serde_pickle_fails_with_interal_tagging() {
    let vec = serde_pickle::to_vec(&Thing::Thing(1.0), true).unwrap();
    let _: Thing = serde_pickle::from_slice(&vec).unwrap();
}
```

In this minimal example, we get the helpful message "cannot serialize tagged newtype variant Thing::Thing containing a float", however the error is more cryptic when structs are nested.

I'd argue that correcting this is worth the "breaking change". I'm happy to help if possible.

**Comment by m-dewanchand** [comment]
Ran into the same issue. Solved it by adding a serde container attribute to the enum: #[serde(into = "String")] and a from<enumtype> for String method.
Example:
```
#[derive(Debug, PartialEq, Copy, Clone, Serialize)]
#[serde(into = "String")]
pub enum Feature {
    CrowdSim,
    Traffic,
    Debug,
    Demo,
    Json,
}

impl From<Feature> for String {
    fn from(src: Feature) -> String {
        format!("{:?}", src)
    }
}
```

**Comment by birkenfeld** [comment]
Ok, the new default is now implemented; if you are still interested it would be nice if you could test out master before I release 1.0.

**Comment by Palladinium** [comment]
I only did some simple testing, but it looks good. Thank you!

**Comment by m-dewanchand** [comment]
Same here, looks good. Thanks!

**Comment by birkenfeld** [comment]
Cool, thanks! I'll go ahead with the release then.

**Comment by m-dewanchand** [comment]
if possible we'd like to send 2 more patches.....can you wait? Hope to send the patches today.

**Comment by birkenfeld** [comment]
Too late - will they be backwards compatible?

**Comment by m-dewanchand** [comment]
I think so....

**Comment by birkenfeld** [comment]
Ok, depending on the timing it'll have to wait about a week since I'm going on vacation tomorrow. But then I can release that as 1.1.
